feat: [memberonteam] add service
tatuga-camp/server-tatuga-school pull request #43
Opened 2024-07-22 17:50 UTC by ChunWarayut

feat: [memberonteam] add service

2024-07-23 08:55 UTC, permlap-phola requested changes

2024-07-23 08:57 UTC, permlap-phola commented on src/board-task/board/board.service.ts
> +      };
ลบ message ออกจาก response

2024-07-23 08:57 UTC, permlap-phola commented on src/board-task/board/board.service.ts
> +        message: 'Boards retrieved successfully',
ลบ message ออกจาก response endpoint ที่เป็น GET POST PATCH ยกเว้น DELETE

2024-07-25 06:51 UTC, permlap-phola commented
@ChunWarayut  รบกวนแก้ pull request มาในวันศุกร์ได้ไหมครับ พอดีผมจะปิด project นี้ภายในสิ้นเดือน

2024-07-30 14:59 UTC, ChunWarayut commented
หมดแล้วนะ

2024-07-31 07:06 UTC, merged